### ISSUE TITLE
Questions around user management

### ISSUE THREAD

**Issue by larsks** [nerc-images/keycloak-ansible#3]
Currently the `Containerfile` includes the follow code:

```sh
ENV \
    GECOS="Keycloak user" \
    HOME="/home/keycloak" \
    UID="185" \
    USER="keycloak"
RUN groupadd -r $USER -g $UID \
  && useradd -u $UID -r -g root -G $USER -m -d $HOME -s /sbin/nologin -c "$GECOS" $USER
RUN cp /etc/passwd $HOME/passwd
RUN chmod ug+rwX $HOME $HOME/passwd

USER 1001
WORKDIR $HOME
```

I'm not sure if this is necessary or useful, but I don't know exactly how you intend to use this image so I may be wrong. In most cases, I would simplify the `Containerfile` down to:

```
FROM registry.access.redhat.com/ubi9:9.3

USER root

# Install pip dependencies
RUN yum install -y python3-pip
COPY requirements.txt requirements.yaml /tmp/
RUN pip install -r /tmp/requirements.txt
RUN ansible-galaxy install -r /tmp/requirements.yaml
```

If you want to run the container as an unprivileged user, that can be done at runtime (e.g., via the `-u <uid>` option, and of course in OpenShift the image will be run with a random UID).

Enforcing a fixed uid like this makes it more difficult to run in OpenShift, and also makes it more difficult to share files locally using bind mounts. Consider a command like this:

```
podman run -it --rm -v $HOME/.kube:/kube keycloak-ansible
```

When running with the `USER 1001` in the `Containerfile`, it won't be possible to access files in `/kube` in the container. On the other hand, if the container runs as `root` by default, this will work as intended.

**Comment by computate** [comment]
@larsks With a Containerfile as you suggested above that runs as root, when I run the [Job for keycloak-permissions](https://github.com/computate/nerc-ocp-config/blob/obs-keycloak/keycloak/overlays/nerc-ocp-obs/jobs/keycloak-permissions/job.yaml#L21-L48) I am developing, I get the following error while running the playbook in the container in OpenShift Local: 

`ERROR: Unable to create local directories(/.ansible/tmp): [Errno 13] Permission denied: b'/.ansible'`

Do you know a better way to allow the container to create a .ansible dir in it's home directory? I basically copied the way this [Red Hat openjdk container configures a user](https://catalog.redhat.com/software/containers/ubi8/openjdk-17/618bdbf34ae3739687568813?architecture=amd64&image=65549bde0d27bb1214f3374f&container-tabs=dockerfile&gti-tabs=registry-tokens).

**Comment by larsks** [comment]
You need to ensure that `HOME` points to a writeable directory. By mounting a volume at some path and ensuring that `$HOME` points at that directory, we can run the image as any uid. For example, the following cli runs the container with a random UID:

```
podman run --read-only -it -v /home/ansible -w /home/ansible -e HOME=/home/ansible --rm -u $(( (RANDOM%5000) + 5000)) keycloak-ansible
```

This works despite the `--read-only` setting:

```
$ podman run --read-only -it -v /home/ansible -w /home/ansible -e HOME=/home/ansible --rm -u $(( (RANDOM%5000) + 5000)) keycloak-ansible
bash-5.1$ ansible localhost -m ping
[WARNING]: No inventory was parsed, only implicit localhost is available
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
bash-5.1$
```

Whereas without setting up `$HOME` it fails:

```
$ podman run --read-only -it --rm -u $(( (RANDOM%5000) + 5000)) keycloak-ansible
bash-5.1$ ansible localhost -m ping
ERROR: Unable to create local directories(/.ansible/tmp): [Errno 30] Read-only file system: b'/.ansible'
```

**Comment by computate** [comment]
@larsks Should I always mount a volume for the job that runs Ansible and creates `~/.ansible`? 
- Should I mount it at `/`, or change the home directory in the Containerfile?

**Comment by computate** [comment]
Ha ha, I guess I probably can't mount `/`.

**Comment by computate** [comment]
@larsks I'll try the suggestion for `ENV HOME=/home/ansible` and a mounted volume.

**Comment by computate** [comment]
Thanks for the suggestions @larsks , my testing with the new `HOME=/home/ansible` seems to work if I create an ephemeral volume there of 100Mi in [my Job](https://github.com/computate/nerc-ocp-config/blob/obs-keycloak/keycloak/overlays/nerc-ocp-obs/jobs/keycloak-permissions/job.yaml#L19-L37). Does that sounds like a good approach?

**Comment by larsks** [comment]
That sounds perfect!
